### ISSUE TITLE
Classifying the biodiversity of the Great Barrier Reef World Heritage Area for the classification phase of the representative areas program

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/mwhs-data-mobilization#1]
- [Folder](https://github.com/iobis/mwhs-data-mobilization/tree/master/datasets/great_barrier_reef_classifying)
- Publication: https://elibrary.gbrmpa.gov.au/jspui/handle/11017/442

> This technical report outlines the methods that the Great Barrier Reef Marine Park Authority used to classify the biodiversity of the marine environs of the Great Barrier Reef World Heritage Area for the Representative Areas Program. Classification was the first step in the multiphase Representative Areas Program that eventuated in a new network of no-take areas, free from extractive activities, in the Great Barrier Reef Marine Park.

**Comment by sunray1** [comment]
Heritage Site that is not included in this project
