### ISSUE TITLE
FishCARD: Fish 12S California Current Specific Reference Database for Enhanced Metabarcoding Efforts

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/mwhs-data-mobilization#4]
- Paper: https://www.authorea.com/users/330161/articles/457029-fishcard-fish-12s-california-current-specific-reference-database-for-enhanced-metabarcoding-efforts
- GitHub: https://github.com/zjgold/FishCARD

**Comment by sunray1** [comment]
Heritage Site that is not included in this project
